FROM ubuntu:18.04

# install (tested) dependencies of kmax/kclause and evaluation scripts
RUN apt-get update && apt-get install -y --allow-unauthenticated \
  git \
  subversion \
  python3-setuptools \
  python3-dev \
  flex \
  bison \
  bc \
  libssl-dev \
  libelf-dev \
  wget

# install (the tested version of) kmax/kclause
WORKDIR /home
RUN git clone https://github.com/paulgazz/kmax.git \
  && cd kmax \
  && git checkout c6e83a07d4f916267cb9e718c0b2de42ecfe4147 \
  && python3 setup.py install

# install dependencies of analyzed projects
RUN apt-get update && apt-get install -y --allow-unauthenticated \
  build-essential

# copy and set up
# - kextractor (which is compiled against the projects' Kconfig implementations)
# - IO and evaluation scripts
COPY kclause/kextractor.c kclause/*.py *.sh ./
RUN chmod +x *.sh